const id = "ash_covid19.md";
						const collection = "projects";
						const slug = "covid19_ash";
						const body = "\r\n### Purpose\r\nThe main purpose of this project is to create a fast COVID-19 dashboard and parser that can raise awareness among the public, visualize data for easy understanding, gather data for research and experiences, and provide a platform for the public to interact with the data.\r\n\r\n### Problems Faced\r\n- Initially I built a backend in the flask to retrieve the data and used Ajax to retrieve the data but the only problem I have is that I do not have a server where I can host other than PHP applications.\r\n- It was very frustrating because of this problem but this thought came to my mind. Instead of retrieving data from the server, we can create static JavaScript files directly and host them on GitHub and create a static site with VueJs.\r\n- So, I made it a success with GitHub Actions [by the way, thanks to GitHub for providing the best functionality].\r\n- The second problem I faced was about enabling frontend sites to support multiple countries but I solved it.\r\n\r\n### Features\r\n- Automated parsing of data from government websites daily using GitHub Actions for multiple countries.\r\n- Automated parsing of data from WHO on every Monday using GitHub Actions.\r\n- Dashboard to visualize data.\r\n- Publicly available data downloading.\r\n- Support for multiple countries on the frontend.\r\n- Super Fast performance.\r\n- Fully customizable for country websites - see the contribution guideline for more information.\r\n\r\n### Some Goodies\r\n- Simple and easy-to-use UI for discovering COVID-19 statistics.\r\n- Easily portable to multiple countries by adding a new scraper and frontend support.\r\n- Highly scalable and fast.\r\n- Publicly available data.\r\n- I enjoyed working in it.\r\n\r\n### Lessons Learnt\r\nAlthough, this was my first project using the selenium and beautiful-soup libraries, so I learned about them along with GitHub Actions.\r\n";
						const data = {startDate:new Date(1596240000000),endDate:new Date(1601510400000),title:"Covid19",stacks:["Python","TypeScript","JavaScript","Vue","Bootstrap"],company:"alphasofthub",live:"https://covid19.alphasofthub.com/",github:"lablnet/covid19",featured:false,draft:false};
						const _internal = {
							type: 'content',
							filePath: "D:/umer/projects/lablnet/lablnet.com/src/content/projects/ash_covid19.md",
							rawData: undefined,
						};

export { _internal, body, collection, data, id, slug };
