const id = "others_weather.md";
						const collection = "projects";
						const slug = "weather";
						const body = "\r\n### ⚠️ Note\r\n- Multithreading does not affect network throughput, as it only splits URLs into multiple threads that wait in the network queue. However, data updating in the file is concurrent, meaning that\r\n    - for example, if the first thread is updating data in the file at the same time the second thread is fetching data from the network, the second thread does not have to wait for the first thread to finish.\r\n\r\n### Purpose\r\nThe sole purpose of this project is to retrieve weather data for Pakistan from the Weather Channel and store it in a database or CSV file. This data can then be used for further analysis. Additionally, I created a simple web app to display the latest weather reports for Pakistan as a fun extension of the project.\r\n\r\n### Woking\r\nThe script runs every hour, using [GitHub Actions](https://github.com/features/actions) to fetch the weather data from the Weather Channel and store it in the database.\r\n\r\n### Data Files\r\nTo avoid creating a large, unwieldy file, the data is stored in multiple files organized by year and month. For example, data for August 2022 would be stored in the file \"/data/2022/aug.csv\" in CSV format. This approach was chosen because storing the data in a single file would make it difficult to read, and GitHub's file size limit of 100MB necessitated the use of multiple files.\r\n\r\nHowever, this approach creates a new problem: it is difficult to read data from multiple files. To address this issue, I plan to create a simple script that will read data from multiple files and store it in a single file.\r\n\r\n### Future Thoughts\r\nIn the future, I plan to monitor the status of the GitHub action and fix any issues that may arise. I will also create a script to merge the data from multiple files into a single file for easier access and analysis.\r\n\r\n";
						const data = {startDate:new Date(1656633600000),endDate:new Date(1657843200000),title:"Pakistan Weather Scrapper",stacks:["Python","React","TailwindCSS"],company:"projects",live:"https://weather.lablnet.com/",github:"lablnet/pakweather_scrapper",featured:false,draft:false};
						const _internal = {
							type: 'content',
							filePath: "D:/umer/projects/lablnet/lablnet.com/src/content/projects/others_weather.md",
							rawData: undefined,
						};

export { _internal, body, collection, data, id, slug };
