const id = "upwork_weareappointments.md";
						const collection = "projects";
						const slug = "upwork_weareappointments";
						const body = "\nProtonCash is an ERP CRM system that is used to manage legal cases and grant funds as loans. Weareappointments is another CRM system that is used to manage leads. These two systems are integrated to provide a comprehensive solution for managing legal cases and identifying potential clients. ProtonCash is specifically designed to handle the financial aspects of legal cases, including the granting of loans and the tracking of payments.\nWeareappointments, on the other hand, is focused on managing the leads generated by the legal firm, including the tracking of client interactions and the scheduling of appointments. Together, these two systems provide a powerful tool for managing legal cases and client relationships.\n";
						const data = {startDate:new Date(1628294400000),endDate:new Date(1628726400000),title:"ProtonCash, Weareappointments",stacks:["PHP","Laravel","React"],company:"upwork",collaborators:[{name:"Muhammad Umer Farooq",picture:"../../assets/images/umer.jpg"}],live:"https://weareappointments.com/",featured:false,draft:false};
						const _internal = {
							type: 'content',
							filePath: "/Users/lablnet/projects/lablnet/lablnet.com/src/content/projects/upwork_weareappointments.md",
							rawData: undefined,
						};

export { _internal, body, collection, data, id, slug };
