name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Instll Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.0.0'
      - name: Install pnpm
        run: npm install -g pnpm
      - uses: actions/checkout@v3
      - run: pnpm install && pnpm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_LABLNET_86A04 }}'
          channelId: live
          projectId: lablnet-86a04
        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks
